#!/bin/bash

DOOM_BIN_NAME="DOOM_BIN_NAME_R"
TEMP_DIR_NAME="/tmp/doom-builder"
DOOM_CONFIG_DIR="$HOME/.config/DOOM_BIN_NAME"

usage() {
    echo "Usage: poom <options>

Options:
  -f, --file          Path to pk3 or wad file to include.
  -w, --base-wad      Path to base wad/pk3 file.
  -h, --help          Print help.
    "
	exit 2
}

FILE_LIST=()
shift $((OPTIND-1))
for arg in "$@"; do
  shift
  case "$arg" in
    '--help')        set -- "$@" '-h'   ;;
    '--file')        set -- "$@" '-f'   ;;
    '--base-wad')    set -- "$@" '-w'   ;;
    *)               set -- "$@" "$arg" ;;
  esac
done

while getopts ":f:w:h" arg
do
	case $arg in
		f) FILE_LIST+=("$OPTARG");;
		w) WAD="$OPTARG";;
		*) usage ;;
	esac
done

cleanup() {
    echo "Cleaning up"
    rm -Rf "$TEMP_DIR_NAME"
}

mkdir -p "$TEMP_DIR_NAME"
mkdir -p "$TEMP_DIR_NAME/files"
trap cleanup EXIT

if [ ! -n "$WAD" ]; then 
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	echo "!!!!!!!!             WARNING                !!!!!!!!"
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "No base WAD file provided, building using Doom demo WAD."
    cp -Rf "$APPDIR/wad/DEMO.WAD" "$TEMP_DIR_NAME/GAME.WAD"
else
    if [ ! -f "$WAD" ]; then 
        if [ -f "${DOOM_CONFIG_DIR}/$WAD" ]; then
            WAD="${DOOM_CONFIG_DIR}/$WAD"
        else
            echo "WAD file $f does not exist"
            exit 1
        fi
    fi
    cp -Rf "$WAD" "$TEMP_DIR_NAME/GAME.WAD"
fi


for idx in "${!FILE_LIST[@]}"
do
    f="${FILE_LIST[idx]}"
    if [ ! -f "$f" ]; then
        if [ -f "${DOOM_CONFIG_DIR}/${f}" ]; then
            f="${DOOM_CONFIG_DIR}/${f}"
        else
            echo "File $f does not exist"
            exit 1
        fi
    fi

    t_name=$(basename "$f" | xargs)
    t_name=$(echo "$t_name" | sed -e "s/ /-/g" -e "s/\"//g" -e "s/\'//g")
    cp -Rf "$f" "$TEMP_DIR_NAME/files/$t_name"
done

cp -Rf "$APPDIR/usr" "$TEMP_DIR_NAME"
cp -Rf "$APPDIR/app/"* "$TEMP_DIR_NAME"

$APPDIR/appimagetool "$TEMP_DIR_NAME" doom
