#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

export PATH="$HERE"/bin:"$HERE"/usr/local/bin:"$PATH"
export LD_LIBRARY_PATH="$HERE"/usr/lib:"$LD_LIBRARY_PATH"
export GZ_DOOM_BIN="$HERE"/usr/local/bin/gzdoom


$GZ_DOOM_BIN "$@"
