#!/bin/bash

export LD_LIBRARY_PATH="$APPDIR"/usr/lib:"$LD_LIBRARY_PATH"

GZDOOM_DIR="$HOME/.config/gzdoom"

f_str=""
for file in "$APPDIR/files"/*
do
    if [ -f "$file" ]; then
        f_str=" -file ${file}"
    fi
done

echo "$f_str"

for file in "$@"
do
    if [ -f "$file" ] || [ -f "${GZDOOM_DIR}/${file}" ]; then
        f_str=" -file ${APPDIR}/files/${file}"
    else
        echo "File $file does not exist"
        exit 1
    fi
done

cmd="${APPDIR}/usr/bin/gzdoom -iwad ${APPDIR}/GAME.WAD ${f_str}"
$cmd
