#!/bin/bash

export LD_LIBRARY_PATH="$APPDIR"/usr/lib:"$LD_LIBRARY_PATH"

GZDOOM_DIR="$HOME/.config/gzdoom"
BASE_WAD="${APPDIR}/GAME.WAD"

usage() {
    echo "Usage: doom <options> <wad_files..>

Built with doom-builder (github.com/exaroth/doom-builder)

Options:
  -h, --help           Show usage
"
	exit 2
}

shift $((OPTIND-1))
for arg in "$@"; do
  shift
  case "$arg" in
    '--help')        set -- "$@" '-h'   ;;
    *)               set -- "$@" "$arg" ;;
  esac
done

ARGS=""
while [ $# -gt 0 ]
do
    unset OPTIND
    unset OPTARG
    while getopts h options
    do
        case $options in
                h) usage
                    ;;
                *)  ;;
        esac
   done
   shift $((OPTIND-1))
   ARGS="${ARGS} $1 "
   shift
done

f_str=""
mods=()
for file in "$APPDIR/files"/*
do
    if [ -f "$file" ]; then
        mods+=($(basename "$file"))
        f_str="${f_str} -file ${file}"
    fi
done

for file in "${ARGS[@]}"
do
    if [ -f "$file" ] || [ -f "${GZDOOM_DIR}/${file}" ]; then
        mods+=($(basename "$file"))
        f_str="${f_str} -file ${file}"
    else
        echo "File $file does not exist"
        exit 1
    fi
done

echo "Enabled WADs:"
echo "Base WAD: $BASE_WAD"
echo "Modifier WADs"
for w in "${mods[@]}"
    do
        echo "- $w"
done 

cmd="${APPDIR}/usr/bin/gzdoom -iwad $BASE_WAD ${f_str}"
$cmd
