#!/bin/bash

export LD_LIBRARY_PATH="$APPDIR"/usr/lib:"$APPDIR"/lib:"$LD_LIBRARY_PATH"

DOOM_BIN_NAME="DOOM_BIN_NAME_R"
DOOM_CONFIG_DIR="$HOME/.config/${DOOM_BIN_NAME}"
BASE_WAD="${APPDIR}/GAME.WAD"

usage() {
    echo "Usage: doom <options> <wad_files..>

Options:
  -h, --help           Show usage

Built with doom-builder (github.com/exaroth/doom-builder)
"
	exit 2
}

shift $((OPTIND-1))
for arg in "$@"; do
  shift
  case "$arg" in
    '--help')        set -- "$@" '-h'   ;;
    *)               set -- "$@" "$arg" ;;
  esac
done

ARGS=""
while [ $# -gt 0 ]
do
    unset OPTIND
    unset OPTARG
    while getopts h options
    do
        case $options in
                h) usage
                    ;;
                *)  ;;
        esac
   done
   shift $((OPTIND-1))
   ARGS="${ARGS} $1 "
   shift
done

eval "ARGS=($ARGS)"
f_str=""
mods=()
for file in "$APPDIR/files"/*
do
    if [ -f "$file" ]; then
        mods+=($(basename "$file"))
        f_str="${f_str} -file ${file}"
    fi
done

cleanup() {
    echo "Cleaning up"
    rm -Rf /tmp/.doom-shrt
}

mkdir /tmp/.doom-shrt
trap cleanup EXIT

for file in "${ARGS[@]}"
do
    if [ -f "$file" ] || [ -f "${DOOM_CONFIG_DIR}/${file}" ]; then
        mods+=("$(basename "$file")")
        t_name=$(basename "$file" | xargs)
        t_name=$(echo "$t_name" | sed -e "s/ /-/g" -e "s/\"//g" -e "s/\'//g")
        t_path="/tmp/.doom-shrt/${t_name}"
        if [ -f "${DOOM_CONFIG_DIR}/${file}" ]; then
            ln -s "$DOOM_CONFIG_DIR/$file" "$t_path"
        else
            ln -s "$file" "$t_path"
        fi
        f_str="${f_str} -file ${t_path}"
    else
        echo "File $file does not exist"
        exit 1
    fi
done

echo "Enabled WADs:"
echo "Base WAD: $BASE_WAD"
echo "Modifier WADs"
for w in "${mods[@]}"
    do
        echo "- $w"
done 

cmd="${APPDIR}/usr/bin/${DOOM_BIN_NAME} -iwad $BASE_WAD ${f_str}"
$cmd
